import type { Card } from "@/types/card";

/**
 * 20 cards across all six categories, conforming to the canonical Card
 * schema (src/types/card.ts). Unlike the original placeholder set, these
 * summarize real, verifiable video game industry news as of August 21,
 * 2026 — each summary independently rewritten in-house (not copy-pasted)
 * and hard-capped at 60 words, per CLAUDE.md's content format rule, with
 * sources[0].url pointing at the real article it's drawn from.
 *
 * Two caveats: `image_url` still uses picsum.photos placeholders — we
 * don't hold rights to real source screenshots/key art yet, so this is
 * stock imagery, not the article's real image. And like_count/comment_count
 * are still plausible mock numbers, since this site has no real engagement
 * data until Phase 4 wires up Supabase.
 */
export const MOCK_CARDS: Card[] = [
  {
    id: "1",
    slug: "metal-gear-solid-master-collection-vol-2-august-27",
    headline: "Metal Gear Solid: Master Collection Vol. 2 launches August 27 with MGS4",
    summary:
      "Konami's Metal Gear Solid: Master Collection Vol. 2 arrives August 27 on PC, PlayStation 5, Xbox Series X|S, Switch, and Switch 2 for $49.99. The bundle includes Metal Gear Solid 4: Guns of the Patriots, the Peace Walker HD Collection, and handheld title Ghost Babel, plus digital art books and the soundtrack. Pre-orders are open now.",
    category: "releases",
    platform_tags: ["pc", "playstation", "xbox", "switch"],
    sources: [{ name: "Forbes", url: "https://www.forbes.com/sites/brianmazique/2026/08/16/metal-gear-solid-master-collection-vol-2-release-date-pre-order/" }],
    image_url: "https://picsum.photos/seed/mgs-master-collection-2/800/600",
    published_at: "2026-08-16T12:00:00Z",
    hype_signal: 80,
    like_count: 241,
    comment_count: 46,
    game: "metal-gear-solid-master-collection-vol-2",
    game_label: "Metal Gear Solid: Master Collection Vol. 2",
  },
  {
    id: "2",
    slug: "elden-ring-tarnished-edition-switch-2-august-28",
    headline: "Elden Ring: Tarnished Edition launches on Switch 2 August 28",
    summary:
      "FromSoftware and Bandai Namco's Elden Ring: Tarnished Edition launches August 28 exclusively on Switch 2 for $79.99, bundling the base game with Shadow of the Erdtree and two new starting classes, Heavy Knight and Idus Knight. PlayStation, Xbox, and PC owners get the same new content separately via the Tarnished Pack DLC, releasing the same day.",
    category: "releases",
    platform_tags: ["switch", "pc", "playstation", "xbox"],
    sources: [{ name: "Nintendo newsroom", url: "https://www.nintendo.com/us/whatsnew/rise-with-elden-ring-tarnished-edition-launching-aug-28-on-nintendo-switch-2/" }],
    image_url: "https://picsum.photos/seed/elden-ring-tarnished-edition/800/1000",
    published_at: "2026-08-17T12:00:00Z",
    hype_signal: 90,
    like_count: 388,
    comment_count: 71,
    game: "elden-ring",
    game_label: "Elden Ring",
  },
  {
    id: "3",
    slug: "once-human-console-launch-august-25",
    headline: "Once Human comes to PS5 and Xbox with crossplay on August 25",
    summary:
      "NetEase's Once Human comes to PlayStation 5 and Xbox Series X|S on August 25 with full crossplay and cross-progression against existing PC players from day one. The console version also introduces a new first-person camera option alongside the game's existing third-person perspective, letting players switch freely between the two during combat and exploration.",
    category: "releases",
    platform_tags: ["pc", "playstation", "xbox"],
    sources: [{ name: "VideoGamer", url: "https://www.videogamer.com/news/once-human-ps5-xbox-release-date-august-2026/" }],
    image_url: "https://picsum.photos/seed/once-human-console/800/650",
    published_at: "2026-08-11T12:00:00Z",
    hype_signal: 66,
    like_count: 103,
    comment_count: 19,
    game: "once-human",
    game_label: "Once Human",
  },
  {
    id: "4",
    slug: "resonance-plague-tale-legacy-august-27-game-pass",
    headline: "Resonance: A Plague Tale Legacy launches August 27, day one on Game Pass",
    summary:
      "Resonance: A Plague Tale Legacy launches August 27 on PC, PlayStation, and Xbox. The game debuts as a day-one addition to Xbox Game Pass Ultimate and PC Game Pass, joining three other day-one titles revealed in this month's second Game Pass wave. It's among the biggest releases capping out August's otherwise quiet schedule.",
    category: "releases",
    platform_tags: ["pc", "playstation", "xbox"],
    sources: [{ name: "Xbox Wire", url: "https://news.xbox.com/en-us/2026/08/18/xbox-game-pass-august-2026-wave-2/" }],
    image_url: "https://picsum.photos/seed/resonance-plague-tale/800/700",
    published_at: "2026-08-18T12:00:00Z",
    hype_signal: 71,
    like_count: 118,
    comment_count: 24,
    game: "resonance-a-plague-tale-legacy",
    game_label: "Resonance: A Plague Tale Legacy",
  },
  {
    id: "5",
    slug: "big-walk-review-metacritic-94",
    headline: "Big Walk launches to the best-reviewed score of 2026 so far",
    summary:
      "House House's Big Walk, from the creators of Untitled Goose Game, launched August 4 on PC and PS Plus to the best Metacritic score of any 2026 release so far: 94 on PC. The cooperative adventure about teamwork and communication peaked at over 46,000 concurrent Steam players the day after launch, with critics near-unanimously positive.",
    category: "reviews",
    platform_tags: ["pc", "playstation"],
    sources: [{ name: "TheGamer", url: "https://www.thegamer.com/big-walk-reviews-among-best-2026/" }],
    image_url: "https://picsum.photos/seed/big-walk-review/800/900",
    published_at: "2026-08-05T12:00:00Z",
    hype_signal: 95,
    like_count: 412,
    comment_count: 88,
    game: "big-walk",
    game_label: "Big Walk",
  },
  {
    id: "6",
    slug: "mortal-shell-2-review",
    headline: "Mortal Shell II review: a far more confident soulslike",
    summary:
      "Mortal Shell II released August 20 to strong reviews, scoring 84 on PC and 85 on PlayStation 5 at Metacritic. Critics highlighted the removal of stamina management, letting players dodge and attack freely, and called it a far more confident soulslike than its predecessor — though several warned its unforgiving difficulty remains a tough sell for newcomers.",
    category: "reviews",
    platform_tags: ["pc", "playstation"],
    sources: [{ name: "GamesRadar+", url: "https://www.gamesradar.com/games/action-rpg/mortal-shell-2-review/" }],
    image_url: "https://picsum.photos/seed/mortal-shell-2-review/800/620",
    published_at: "2026-08-20T12:00:00Z",
    hype_signal: 83,
    like_count: 197,
    comment_count: 42,
    game: "mortal-shell-2",
    game_label: "Mortal Shell II",
  },
  {
    id: "7",
    slug: "mafia-old-country-man-of-honor-review",
    headline: "Mafia: The Old Country's Man of Honor DLC review is mixed-to-positive",
    summary:
      "Mafia: The Old Country's Man of Honor DLC launched August 14, adding a roughly two-hour story arc set in winter 1905 that slots between the base game's fifth and sixth chapters. Reviews were mixed-to-positive: critics praised the writing and a glimpse of a younger Ennio Salieri, but said clunky shooting and sparse open-world content hold it back.",
    category: "reviews",
    platform_tags: ["pc", "playstation", "xbox"],
    sources: [{ name: "DualShockers", url: "https://www.dualshockers.com/mafia-the-old-country-man-of-honor-review/" }],
    image_url: "https://picsum.photos/seed/mafia-old-country-dlc/800/750",
    published_at: "2026-08-19T12:00:00Z",
    hype_signal: 61,
    like_count: 74,
    comment_count: 16,
    game: "mafia-the-old-country",
    game_label: "Mafia: The Old Country",
  },
  {
    id: "8",
    slug: "valorant-patch-13-04-act-5",
    headline: "VALORANT patch 13.04 kicks off Act 5, brings Abyss back",
    summary:
      "Riot's VALORANT patch 13.04 went live August 18, kicking off Act 5 and rotating Abyss back into the competitive and deathmatch map pools while pulling Breeze out. The update also fixes several Agent bugs, including melee-skin transform animations, Cypher's minimap icon, and Deadlock's GravNet effect disappearing after a disconnect. The new act runs five weeks.",
    category: "patches",
    platform_tags: ["pc"],
    sources: [{ name: "Riot Games", url: "https://playvalorant.com/en-us/news/game-updates/valorant-patch-notes-13-04/" }],
    image_url: "https://picsum.photos/seed/valorant-patch-1304/800/600",
    published_at: "2026-08-18T12:00:00Z",
    hype_signal: null,
    like_count: 88,
    comment_count: 21,
    game: "valorant",
    game_label: "VALORANT",
  },
  {
    id: "9",
    slug: "overwatch-2-patch-august-11-life-grip",
    headline: "Overwatch 2's August patch reworks Life Grip, buffs Cassidy",
    summary:
      "Blizzard's August 11 Overwatch 2 patch reworked Lifeweaver's Life Grip, letting pulled players manually cancel the effect with Jump after 0.6 seconds and slowing the pull speed from 30 to 25 meters per second for a bigger reaction window. Cassidy also gained a movement-speed boost after Combat Roll that decays over 1.5 seconds.",
    category: "patches",
    platform_tags: ["pc", "playstation", "xbox"],
    sources: [{ name: "Blizzard Entertainment", url: "https://overwatch.blizzard.com/en-us/news/patch-notes/live/2026/08/" }],
    image_url: "https://picsum.photos/seed/overwatch-2-patch-aug/800/650",
    published_at: "2026-08-11T12:00:00Z",
    hype_signal: null,
    like_count: 65,
    comment_count: 18,
    game: "overwatch-2",
    game_label: "Overwatch 2",
  },
  {
    id: "10",
    slug: "fallout-4-august-update-creations",
    headline: "Fallout 4's August update targets Creations stability, save warning included",
    summary:
      "Bethesda shipped a Fallout 4 update on August 18 focused on Creations-related fixes and stability improvements. The studio urged players to manually save their current load order before updating, warning that some existing Creations content could be affected by the changes. No new quest or story content was included in this patch.",
    category: "patches",
    platform_tags: ["pc", "playstation", "xbox"],
    sources: [{ name: "ScreenRant", url: "https://screenrant.com/fallout-4-august-2026-update-warning/" }],
    image_url: "https://picsum.photos/seed/fallout-4-august-update/800/700",
    published_at: "2026-08-18T12:00:00Z",
    hype_signal: null,
    like_count: 53,
    comment_count: 27,
    game: "fallout-4",
    game_label: "Fallout 4",
  },
  {
    id: "11",
    slug: "ea-55-billion-buyout-closes",
    headline: "EA's $55 billion buyout officially closes, layoffs feared",
    summary:
      "Electronic Arts officially went private on August 4 after a $55 billion buyout by a consortium led by Saudi Arabia's PIF, alongside Silver Lake and Affinity Partners, closed, ending 37 years as a public company. EA already cut staff three times earlier in 2026 while targeting $700 million in annual savings, fueling fears of further layoffs at studios like BioWare.",
    category: "industry",
    platform_tags: [],
    sources: [{ name: "GameSpot", url: "https://www.gamespot.com/articles/ea-has-officially-been-sold-and-what-comes-next-could-be-painful/" }],
    image_url: "https://picsum.photos/seed/ea-buyout-closes/800/600",
    published_at: "2026-08-04T12:00:00Z",
    hype_signal: null,
    like_count: 156,
    comment_count: 94,
    game: null,
    game_label: null,
  },
  {
    id: "12",
    slug: "xbox-reset-3200-layoffs-four-studios",
    headline: "Xbox's \"Reset\" memo confirms 3,200 layoffs, four studios closed",
    summary:
      "Xbox CEO Asha Sharma's \"Reset\" memo, published July 6, confirmed roughly 3,200 layoffs over the following year and the closure of four internal studios. Sharma cited $20 billion spent on content and hardware subsidies over five years against nearly half a billion dollars in declining annual revenue, and signaled a more affordable Xbox console is under consideration.",
    category: "industry",
    platform_tags: ["xbox"],
    sources: [{ name: "Fortune", url: "https://fortune.com/2026/07/06/exclusive-xbox-ceo-asha-sharma-job-cuts-studios-axed-layoffs/" }],
    image_url: "https://picsum.photos/seed/xbox-reset-layoffs/800/650",
    published_at: "2026-07-06T12:00:00Z",
    hype_signal: null,
    like_count: 203,
    comment_count: 132,
    game: null,
    game_label: null,
  },
  {
    id: "13",
    slug: "ubisoft-quieter-2026-new-ac-far-cry-ghost-recon",
    headline: "Ubisoft confirms new Assassin's Creed, Far Cry, and Ghost Recon are coming",
    summary:
      "Ubisoft reaffirmed that new entries in Assassin's Creed, Far Cry, and Ghost Recon are all in development, even as executives described 2026 as a deliberately \"quieter\" year for the publisher. The comments came ahead of Ubisoft's Gamescom 2026 showing, where Rainbow Six Siege, Anno 117: Pax Romana, and Assassin's Creed Shadows are among the playable lineup.",
    category: "industry",
    platform_tags: [],
    sources: [{ name: "PC Gamer", url: "https://www.pcgamer.com/gaming-industry/ubisoft-promises-new-assassins-creed-far-cry-and-ghost-recon-games-are-coming-but-says-this-year-will-be-quieter-than-most/" }],
    image_url: "https://picsum.photos/seed/ubisoft-2026-slate/800/620",
    published_at: "2026-08-12T12:00:00Z",
    hype_signal: null,
    like_count: 91,
    comment_count: 37,
    game: null,
    game_label: null,
  },
  {
    id: "14",
    slug: "cs2-esports-world-cup-2026-playoffs-paris",
    headline: "CS2's Esports World Cup playoffs begin with Vitality, Spirit, Falcons on one side",
    summary:
      "The CS2 Esports World Cup 2026 playoffs run August 19-23 in Paris for a $2 million prize pool, after group-stage upsets sent Team Spirit and Team Vitality into the lower bracket. Vitality, Spirit, and Team Falcons all landed in the same half of the playoff bracket, guaranteeing at least one of the three misses the grand final.",
    category: "esports",
    platform_tags: ["pc"],
    sources: [{ name: "Dot Esports", url: "https://dotesports.com/counter-strike/news/cs2-ewc-2026-schedule-results" }],
    image_url: "https://picsum.photos/seed/cs2-ewc-2026-paris/800/900",
    published_at: "2026-08-19T12:00:00Z",
    hype_signal: 88,
    like_count: 174,
    comment_count: 39,
    game: "counter-strike-2",
    game_label: "Counter-Strike 2",
  },
  {
    id: "15",
    slug: "team-falcons-rocket-league-ewc-2026-champions",
    headline: "Team Falcons sweep Rocket League's Esports World Cup grand final 4-0",
    summary:
      "Saudi org Team Falcons swept Spacestation Gaming 4-0 in the Rocket League grand final at Esports World Cup 2026 in Paris on August 16, claiming the team's first title in the game. Falcons player Sami \"Dralii\" Hajji became the first competitor to win three separate Esports World Cup championships, each with a different roster.",
    category: "esports",
    platform_tags: ["pc"],
    sources: [{ name: "Esports.gg", url: "https://esports.gg/news/rocket-league/ewc-2026-rocket-league-overview-results/" }],
    image_url: "https://picsum.photos/seed/rocket-league-ewc-falcons/800/650",
    published_at: "2026-08-16T12:00:00Z",
    hype_signal: 79,
    like_count: 149,
    comment_count: 31,
    game: "rocket-league",
    game_label: "Rocket League",
  },
  {
    id: "16",
    slug: "fortnite-reload-elite-series-championship-finals",
    headline: "Fortnite's Reload Elite Series Championship reaches its Finals stage tomorrow",
    summary:
      "Fortnite's Reload Elite Series Championship reaches its Finals stage August 22 in Paris as part of Esports World Cup 2026, after a Group Stage on August 19-20 narrowed the 40-duo field. The last 20 teams will play up to 15 matches for a $1 million prize pool and Esports World Cup Club Championship points.",
    category: "esports",
    platform_tags: ["pc"],
    sources: [{ name: "The Click", url: "https://www.theclick.gg/fortnite-reload-elite-series-championship-2026-2/" }],
    image_url: "https://picsum.photos/seed/fortnite-reload-finals/800/700",
    published_at: "2026-08-20T12:00:00Z",
    hype_signal: 75,
    like_count: 96,
    comment_count: 22,
    game: "fortnite",
    game_label: "Fortnite",
  },
  {
    id: "17",
    slug: "psn-ready-set-play-sale-4600-deals",
    headline: "PSN's \"Ready, Set, Play\" sale discounts over 4,600 games and add-ons",
    summary:
      "PlayStation Store's \"Ready, Set, Play\" sale runs through August 26 with more than 4,600 PS4 and PS5 games, DLC, and add-ons discounted up to 75%. Highlights include Black Myth: Wukong at 30% off, its lowest price yet, alongside steep cuts across sports titles and Assassin's Creed add-ons. No PS Plus membership is required to buy sale items.",
    category: "deals",
    platform_tags: ["playstation"],
    sources: [{ name: "Push Square", url: "https://www.pushsquare.com/features/40plus-ps5-ps4-games-to-buy-in-ps-stores-ready-set-play-sale" }],
    image_url: "https://picsum.photos/seed/psn-ready-set-play/800/600",
    published_at: "2026-08-18T12:00:00Z",
    hype_signal: null,
    like_count: 112,
    comment_count: 26,
    game: null,
    game_label: null,
  },
  {
    id: "18",
    slug: "xbox-game-pass-august-wave-2",
    headline: "Xbox Game Pass's second August wave adds four day-one titles",
    summary:
      "Xbox's second Game Pass wave for August adds ten titles, including four day-one releases: Vapor World: Over the Mind, Blood Dungeon, Resonance: A Plague Tale Legacy, and September's Shelldiver. Premium tier subscribers also gain Relooted, an Africanfuturist heist game about recovering looted artifacts, and BlazBlue Entropy Effect X, among others rolling out through late August.",
    category: "deals",
    platform_tags: ["xbox", "pc"],
    sources: [{ name: "Xbox Wire", url: "https://news.xbox.com/en-us/2026/08/18/xbox-game-pass-august-2026-wave-2/" }],
    image_url: "https://picsum.photos/seed/xbox-game-pass-wave-2/800/650",
    published_at: "2026-08-18T12:00:00Z",
    hype_signal: null,
    like_count: 134,
    comment_count: 29,
    game: null,
    game_label: null,
  },
  {
    id: "19",
    slug: "epic-games-store-free-cardpocalypse",
    headline: "Epic Games Store's free weekly game is deck-builder Cardpocalypse",
    summary:
      "Epic Games Store's current weekly freebie is deck-builder Cardpocalypse, free to claim through August 27 alongside a bonus Epic Mage Bundle DLC pack for free-to-play MMORPG Albion Online. As always, claiming requires a free Epic account with two-factor authentication enabled; next week's replacement title unlocks automatically once the current offer expires.",
    category: "deals",
    platform_tags: ["pc"],
    sources: [{ name: "Beebom", url: "https://beebom.com/epic-games-free-games-list/" }],
    image_url: "https://picsum.photos/seed/epic-store-cardpocalypse/800/700",
    published_at: "2026-08-20T12:00:00Z",
    hype_signal: null,
    like_count: 68,
    comment_count: 11,
    game: "cardpocalypse",
    game_label: "Cardpocalypse",
  },
  {
    id: "20",
    slug: "steam-weeklong-sale-95-percent-off",
    headline: "Steam's Weeklong Sale cuts over 4,500 games up to 95% off",
    summary:
      "Steam's latest Weeklong Sale runs through August 24 with more than 4,500 games discounted up to 95%. Notable cuts include Kingdom Come: Deliverance 2 at 60% off and its Royal Edition at 60%, the original Kingdom Come: Deliverance Royal Edition at 80% off, and horror title Witchfire at 20% off its recent price.",
    category: "deals",
    platform_tags: ["pc"],
    sources: [{ name: "GG.deals", url: "https://gg.deals/deal/steams-new-weeklong-sale-goes-big-with-thousands-of-games-and-deals-up-to-95-off/" }],
    image_url: "https://picsum.photos/seed/steam-weeklong-sale-95/800/620",
    published_at: "2026-08-19T12:00:00Z",
    hype_signal: null,
    like_count: 87,
    comment_count: 15,
    game: null,
    game_label: null,
  },
];
