import type { Metadata } from "next";
import Link from "next/link";
import { CONTACT_EMAIL, SITE_OPERATOR } from "@/lib/legal";

export const metadata: Metadata = {
  title: "About Us",
  description: `About ${SITE_OPERATOR} — an Inshorts-style, 60-word news site for the video game industry.`,
};

export default function AboutPage() {
  return (
    <div className="mx-auto w-full max-w-3xl px-4 py-10">
      <h1 className="mb-6 text-2xl font-bold text-foreground">About {SITE_OPERATOR}</h1>

      <div className="flex flex-col gap-5 text-sm leading-relaxed text-foreground-muted">
        <p>
          {SITE_OPERATOR} is a card-based news site that summarizes video game
          industry news — releases, reviews, patches, esports, and deals —
          into strict 60-word cards. New cards are added automatically every
          couple of hours, with faster updates during major showcases like
          Nintendo Direct, State of Play, and Xbox events.
        </p>

        <p>
          Every card is a rewritten summary of reporting that originally
          appeared elsewhere. We don&apos;t do original journalism — we curate
          and condense coverage from established gaming publishers so you can
          scan the day&apos;s news in seconds, and every card links back to
          the original source for the full story.
        </p>

        <h2 className="mt-2 text-lg font-semibold text-foreground">
          What we cover
        </h2>
        <p>
          Releases &amp; launches, reviews, patches &amp; updates, industry
          &amp; business news, esports, and deals &amp; sales — tagged by
          platform (PC, PlayStation, Xbox, Nintendo, Mobile, VR) so you can
          filter down to what you actually play.
        </p>

        <h2 className="mt-2 text-lg font-semibold text-foreground">
          How it works
        </h2>
        <p>
          Cards are generated by an automated pipeline that pulls from a
          curated list of gaming outlets, rewrites each story into a 60-word
          summary, categorizes and tags it, and publishes it — refreshed on a
          standing schedule around the clock.
        </p>

        <h2 className="mt-2 text-lg font-semibold text-foreground">
          Get in touch
        </h2>
        <p>
          Questions, corrections, or takedown requests — see{" "}
          <Link href="/contact" className="font-medium text-accent hover:text-accent-hover">
            Contact Us
          </Link>{" "}
          or email{" "}
          <a
            href={`mailto:${CONTACT_EMAIL}`}
            className="font-medium text-accent hover:text-accent-hover"
          >
            {CONTACT_EMAIL}
          </a>
          .
        </p>
      </div>
    </div>
  );
}
